version: "3"
services:
  rabbitmq:
    #build: ./rasa/
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      replicas: 1
    restart: always
  api:
    #build: ./rasa/
    image: assignment_api:latest
    ports:
      - 8000:8000
    deploy:
      replicas: 1
    restart: always
    depends_on:
      - rabbitmq
  worker:
    #build: ./
    image: assignment_worker:latest
    ports:
      - 8082:8082
    volumes:
      - ../worker/geography.db:/app/geography.db
    restart: always
    depends_on:
      - rabbitmq
